# Generated by Django 3.2.10 on 2023-01-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221223_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
